export const chartsMockData = [
    {
        id: 1,
        name: 'Ahmet Yılmaz',
        age: 25,
        city: 'İstanbul',
        gender: 'Erkek',
    },
    {
        id: 2,
        name: 'Ayşe Demir',
        age: 32,
        city: 'Ankara',
        gender: 'Kadın',
    },
    {
        id: 3,
        name: 'Mehmet Kaya',
        age: 29,
        city: 'İzmir',
        gender: 'Erkek',
    },
    {
        id: 4,
        name: 'Zeynep Şahin',
        age: 27,
        city: 'Bursa',
        gender: 'Kadın',
    },
    {
        id: 5,
        name: 'Fatma Gül',
        age: 31,
        city: 'Antalya',
        gender: 'Kadın',
    },
    {
        id: 6,
        name: 'Mustafa Arslan',
        age: 28,
        city: 'Adana',
        gender: 'Erkek',
    },
    {
        id: 7,
        name: 'Emine Öztürk',
        age: 30,
        city: 'Gaziantep',
        gender: 'Kadın',
    },
    {
        id: 8,
        name: 'Ali Aksoy',
        age: 26,
        city: 'Konya',
        gender: 'Erkek',
    },
    {
        id: 9,
        name: 'Hülya Okur',
        age: 33,
        city: 'Eskişehir',
        gender: 'Kadın',
    },
    {
        id: 10,
        name: 'Osman Avcı',
        age: 24,
        city: 'Denizli',
        gender: 'Erkek',
    },
    {
        id: 11,
        name: 'Hatice Kara',
        age: 29,
        city: 'Kocaeli',
        gender: 'Kadın',
    },
    {
        id: 12,
        name: 'Veli Can',
        age: 31,
        city: 'Kayseri',
        gender: 'Erkek',
    },
    {
        id: 13,
        name: 'Esra Tuncer',
        age: 27,
        city: 'Trabzon',
        gender: 'Kadın',
    },
    {
        id: 14,
        name: 'Süleyman Yıldırım',
        age: 28,
        city: 'Malatya',
        gender: 'Erkek',
    },
    {
        id: 15,
        name: 'Gülşah Ateş',
        age: 30,
        city: 'Konya',
        gender: 'Kadın',
    },
    {
        id: 16,
        name: 'Kemal Yavuz',
        age: 26,
        city: 'İzmit',
        gender: 'Erkek',
    },
    {
        id: 17,
        name: 'Sevim Durak',
        age: 32,
        city: 'Adana',
        gender: 'Kadın',
    },
    {
        id: 18,
        name: 'Hasan Erdoğan',
        age: 29,
        city: 'Mersin',
        gender: 'Erkek',
        gender: 'Kadın',
    },
    {
        id: 19,
        name: 'Serap Özcan',
        age: 25,
        city: 'Muğla',
        gender: 'Kadın',
    },
    {
        id: 20,
        name: 'Metin Uysal',
        age: 31,
        city: 'Balıkesir',
        gender: 'Erkek',
    },
    {
        id: 21,
        name: 'Gülay Taş',
        age: 27,
        city: 'Rize',
        gender: 'Kadın',
    },
    {
        id: 22,
        name: 'Emir Aksu',
        age: 28,
        city: 'Van',
        gender: 'Erkek',
    },
    {
        id: 23,
        name: 'Nevin Coşkun',
        age: 30,
        city: 'Erzurum',
        gender: 'Kadın',
    }
]
