


export const usersMockData = [
    { "id": "1", "name": "Ahmet", "lastname": "Yılmaz" },
    { "id": "2", "name": "Ayşe", "lastname": "Kaya" },
    { "id": "3", "name": "Mehmet", "lastname": "Arslan" },
    { "id": "4", "name": "Zeynep", "lastname": "Can" },
    { "id": "5", "name": "Emre", "lastname": "Demir" },
    { "id": "6", "name": "Fatma", "lastname": "Tekin" },
    { "id": "7", "name": "Ali", "lastname": "Güneş" },
    { "id": "8", "name": "Nur", "lastname": "Özdemir" },
    { "id": "9", "name": "Hüseyin", "lastname": "Aydın" },
    { "id": "10", "name": "Elif", "lastname": "Koç" },
    { "id": "11", "name": "Mustafa", "lastname": "Çelik" },
    { "id": "12", "name": "Gamze", "lastname": "Ergin" },
    { "id": "13", "name": "Yusuf", "lastname": "Durmaz" },
    { "id": "14", "name": "Selin", "lastname": "Yıldırım" },
    { "id": "15", "name": "Ömer", "lastname": "Sarı" },
    { "id": "16", "name": "Zehra", "lastname": "Aktaş" },
    { "id": "17", "name": "Cem", "lastname": "Yavuz" },
    { "id": "18", "name": "Aslı", "lastname": "Tuncer" },
    { "id": "19", "name": "Murat", "lastname": "Eren" },
    { "id": "20", "name": "Deniz", "lastname": "Turan" },
    { "id": "21", "name": "Seda", "lastname": "Taş" },
    { "id": "22", "name": "Eren", "lastname": "Aksoy" },
    { "id": "23", "name": "Ceren", "lastname": "Toker" },
    { "id": "24", "name": "Tolga", "lastname": "Kurt" },
    { "id": "25", "name": "İrem", "lastname": "Bulut" },
    { "id": "26", "name": "Berkay", "lastname": "Çakır" },
    { "id": "27", "name": "Ebru", "lastname": "Yılmaz" },
    { "id": "28", "name": "Kadir", "lastname": "Atalay" },
    { "id": "29", "name": "Pelin", "lastname": "Şahin" },
    { "id": "30", "name": "Türker", "lastname": "Kabak" }
]